/**
 * Entity/ComponentTypes.hpp
 *  (c) Jonathan Capps
 *  Created 07 Sept. 2011
 */

#ifndef COMPONENT_TYPES_HPP
#define COMPONENT_TYPES_HPP

enum COMPONENT_TYPE
{
	COMPONENT_CAMERA,
	COMPONENT_MOVABLE,
	COMPONENT_RENDERABLE,
	COMPONENT_XFORM
};

#endif // COMPONENT_TYPES_HPP
