/**
 *  Input/ActionConstants.hpp
 *  (c) Jonathan Capps
 *  Created 12 Sept. 2011
 */

#ifndef ACTION_CONSTANTS_HPP
#define ACTION_CONSTANTS_HPP

enum ACTION
{
	ACTION_MOVE_RIGHT,
	ACTION_MOVE_UP,
	ACTION_MOVE_LEFT,
	ACTION_MOVE_DOWN,
	ACTION_SELECT,
	ACTION_EXIT
};

#endif //ACTION_CONSTANTS_HPP
